# Generated by Django 3.2.3 on 2021-05-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
