# Generated by Django 3.2.3 on 2021-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
